export const contentDB=[
{id:1, title:"Введение в веб-разработку",
	dots:[{id:1,title:'Знакомимся с HTML'},{id:2,title:'Hello, world'}],text:"",triger:""},
{id:2, title:"HTML и введение в CSS",
	dots:[{id:0,title:'списки'}, {id:1,title:'формы'}, {id:2,title:'таблицы'}, {id:3,title:'CSS: селекторы, margin, padding'}],text:"",triger:""},
{id:3, title:"Оформление элементов",
	dots:[{id:0,title:'Работа со шрифтами и фоном'}, {id:1,title:'Блочная модель'}, {id:2,title:'Float'}, {id:3,title:'inline-block'}, {id:4,title:'Flex-модель'}],text:"",triger:""},
{id:4, title:"Состояние и позиционирование элементов",
	dots:[{id:0,title:'Hover, active и focus элементов'}, {id:1,title:'Псевдоэлементы'}, {id:2,title:'Позиционирование элементов'}],text:"",triger:""},
{id:5, title:"Углубление в HTML5 и CSS3",
	dots:[{id:0,title:'Семантика'}, {id:1,title:'Аудио и видео'}, {id:2,title:'Новые стили в CSS3'}, {id:3,title:'Анимации'}],text:"",triger:""},
{id:6, title:"Анимация элементов",
	dots:[{id:0,title:'Линейная анимация transition'}, {id:1,title:'Цикличная анимация keyframes'}],text:"",triger:""},
{id:7, title:"Формы",
	dots:[{id:0,title:'Работа с формами'}, {id:1,title:'Работа с полями ввода'}],text:"",triger:""},
{id:8, title:"Адаптивная и резиновая верстка",
	dots:[{id:0,title:'Сетка сайта'}, {id:1,title:'Adaptive, responsive'}, {id:2,title:'Мобильная верстка'}],text:"",triger:""},
{id:9, title:"Grid",
	dots:[],text:"",triger:""},
{id:10, title:"Bootstrap",
	dots:[],text:"",triger:""},
{id:11, title:"Эволюция CSS",
	dots:[],text:"",triger:""},
{id:12, title:"Проектирование",dots:[],text:"",triger:""},
{id:13, title:"Введение в FrontEnd. Git",dots:[],text:"",triger:""},
{id:14, title:"Введение в JavaScript",dots:[],text:"",triger:""},
{id:15, title:"Основы JavaScript",dots:[],text:"",triger:""},
{id:16, title:"Объекты и массивы.",dots:[],text:"",triger:""},
{id:17, title:"Объекты и массивы.",dots:[],text:"",triger:""},
{id:18, title:"Введение в функции",dots:[],text:"",triger:""},
{id:19, title:"Функции: LevelUP",dots:[],text:"",triger:""},
{id:20, title:"DOM",dots:[],text:"",triger:""},
{id:21, title:"Cобытия",dots:[],text:"",triger:""},
{id:22, title:"BOM",dots:[],text:"",triger:""},
{id:23, title:"Взаимодействие с сетью + Ajax",dots:[],text:"",triger:""}
];


