export const contentDB=[
{id:1, title:"Введение в веб-разработку",dots:['Знакомимся с HTML','Hello, world'],text:"",triger:""},
{id:2, title:"HTML и введение в CSS",dots:['списками', 'формами', 'таблицам', 'CSS: селекторы, margin, padding'],text:"",triger:""},
{id:3, title:"Оформление элементов",dots:['Работа со шрифтами и фоном', 'Блочная модель', 'Float', 'inline-block', 'Flex-модель'],text:"",triger:""},
{id:4, title:"Состояние и позиционирование элементов",dots:['Hover, active и focus элементов', 'Псевдоэлементы', 'Позиционирование элементов'],text:"",triger:""},
{id:5, title:"Углубление в HTML5 и CSS3",dots:['Семантика', 'Аудио и видео', 'Новые стили в CSS3', 'Анимации'],text:"",triger:""},
{id:6, title:"Анимация элементов",dots:[],text:"",triger:""},
{id:7, title:"Формы",dots:[],text:"",triger:""},
{id:8, title:"Адаптивная и резиновая верстка",dots:[],text:"",triger:""},
{id:9, title:"Grid",dots:[],text:"",triger:""},
{id:10, title:"Bootstrap",dots:[],text:"",triger:""},
{id:11, title:"Эволюция CSS",dots:[],text:"",triger:""},
{id:12, title:"Проектирование",text:"",triger:""},
{id:13, title:"Введение в FrontEnd. Git",text:"",triger:""},
{id:14, title:"Введение в JavaScript",text:"",triger:""},
{id:15, title:"Основы JavaScript",text:"",triger:""},
{id:16, title:"Объекты и массивы.",text:"",triger:""},
{id:17, title:"Объекты и массивы.",text:"",triger:""},
{id:18, title:"Введение в функции",text:"",triger:""},
{id:19, title:"Функции: LevelUP",text:"",triger:""},
{id:20, title:"DOM",text:"",triger:""},
{id:21, title:"Cобытия",text:"",triger:""},
{id:22, title:"BOM",text:"",triger:""},
{id:23, title:"Взаимодействие с сетью + Ajax",text:"",triger:""},
];


